NodeFile: /Users/apple/Desktop/buaa/data/filter_result/liantong_n.csv
EdgeFile: /Users/apple/Desktop/buaa/data/filter_result/liantong_e.csv
OutputDir: /Users/apple/Desktop/buaa/code/dmine-pro/output/dmineresult/
NodeXLabel: 4
NodeYLabel: 7
EdgeQLabel: 3
SuppRLimit: 100
Radius: 5
TopK: 30
  