NodeFile: /Users/apple/Desktop/buaa/data/biokg/biokg_v.csv
EdgeFile: /Users/apple/Desktop/buaa/data/biokg/biokg_e.csv
OutputDir: /Users/apple/Desktop/buaa/code/dmine-pro/output/dmineresult/
NodeXLabel: 51
NodeYLabel: 55
EdgeQLabel: 1
SuppRLimit: 440
Radius: 4
TopK: 45