include(FindPackageHandleStandardArgs)

set(LIBGLOG_ROOT_DIR "" CACHE PATH "Folder contains LIBGLOG")

find_path(LIBGLOG_INCLUDE_DIR glog PATHS ${LIBGLOG_ROOT_DIR})

find_library(LIBGLOG_LIBRARY glog)

find_package_handle_standard_args(LIBGLOG DEFAULT_MSG LIBGLOG_INCLUDE_DIR LIBGLOG_LIBRARY)

if(LIBGLOG_FOUND)
    set(LIBGLOG_INCLUDE_DIRS ${LIBGLOG_INCLUDE_DIR})
    set(LIBGLOG_LIBRARIES ${LIBGLOG_LIBRARY})
    message(STATUS "Found LIBGLOG  (include: ${LIBGLOG_INCLUDE_DIR}, library: ${LIBGLOG_LIBRARY})")
    mark_as_advanced(LIBGLOG_LIBRARY_DEBUG LIBGLOG_LIBRARY_RELEASE
                     LIBGLOG_LIBRARY LIBGLOG_INCLUDE_DIR LIBGLOG_ROOT_DIR)
endif()
